-- Enable uuid-ossp extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create Enums
CREATE TYPE table_status AS ENUM ('available', 'seated');
CREATE TYPE order_status AS ENUM ('placed', 'preparing', 'ready', 'served');
CREATE TYPE user_role AS ENUM ('waiter', 'kitchen', 'admin');
CREATE TYPE assistance_status AS ENUM ('pending', 'resolved');

-- 1. Restaurants Table
CREATE TABLE public.restaurants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    hide_customer_total BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. User Roles Table (Mapping Auth UUID to Role & Restaurant)
CREATE TABLE public.user_roles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    role user_role NOT NULL
);

-- 3. Tables Table
CREATE TABLE public.tables (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    table_number TEXT NOT NULL,
    qr_token TEXT UNIQUE NOT NULL, -- Static token glued to table
    status table_status DEFAULT 'available'::table_status NOT NULL,
    capacity INTEGER DEFAULT 4 NOT NULL,
    UNIQUE(restaurant_id, table_number)
);

-- 4. Menu Items Table
CREATE TABLE public.menu_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    is_available BOOLEAN DEFAULT true NOT NULL,
    is_popular BOOLEAN DEFAULT false NOT NULL
);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.restaurants;
ALTER PUBLICATION supabase_realtime ADD TABLE public.assistance_requests;

-- 5. Orders Table
CREATE TABLE public.orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    table_id UUID REFERENCES public.tables(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL, -- UUID generated by customer app
    status order_status DEFAULT 'placed'::order_status NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of items for simplicity, or we could normalize it
    chef_instructions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Assistance Requests Table
CREATE TABLE public.assistance_requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    table_id UUID REFERENCES public.tables(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    request_type TEXT NOT NULL, -- e.g., 'Water', 'Napkins', 'Waiter called'
    status assistance_status DEFAULT 'pending'::assistance_status NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ROW LEVEL SECURITY (RLS) --

ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assistance_requests ENABLE ROW LEVEL SECURITY;

-- Helper Function to get the current user's restaurant_id
CREATE OR REPLACE FUNCTION get_user_restaurant_id()
RETURNS UUID AS $$
    SELECT restaurant_id FROM public.user_roles WHERE user_id = auth.uid() LIMIT 1;
$$ LANGUAGE sql SECURITY DEFINER;

-- Restaurants Policies
CREATE POLICY "Anyone can view restaurants" ON public.restaurants
    FOR SELECT TO public
    USING (true);

CREATE POLICY "Staff can update their restaurant" ON public.restaurants
    FOR UPDATE TO authenticated
    USING (id = get_user_restaurant_id());

-- User Roles Policies
CREATE POLICY "Users can view their own role" ON public.user_roles
    FOR SELECT TO authenticated
    USING (user_id = auth.uid());

-- Tables Policies
CREATE POLICY "Anyone can view tables" ON public.tables
    FOR SELECT TO public
    USING (true);

CREATE POLICY "Staff can update tables in their restaurant" ON public.tables
    FOR UPDATE TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

-- Menu Items Policies
CREATE POLICY "Anyone can view menu items" ON public.menu_items
    FOR SELECT TO public
    USING (true);

CREATE POLICY "Staff can update menu items in their restaurant" ON public.menu_items
    FOR UPDATE TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

-- Orders Policies

-- 1. Customers can INSERT if they have the correct session token mapping to the table
-- Note: In a real app, you might want to verify the session_token matches the table's current_qr_token via a trigger or security definer function,
-- but for RLS we can allow inserts and rely on the client passing the token.
CREATE POLICY "Customers can create orders" ON public.orders
    FOR INSERT TO public
    WITH CHECK (true); 

-- 2. Customers can SELECT their own orders based on the session token
CREATE POLICY "Customers can view own orders by session token" ON public.orders
    FOR SELECT TO public
    USING (true); -- In practice, the client will filter `WHERE session_id = '...'` 

-- 3. Staff can SELECT all orders in their restaurant
CREATE POLICY "Staff can view restaurant orders" ON public.orders
    FOR SELECT TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

-- 4. Staff can UPDATE all orders in their restaurant
CREATE POLICY "Staff can update restaurant orders" ON public.orders
    FOR UPDATE TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

-- 5. Staff can DELETE orders in their restaurant
CREATE POLICY "Staff can delete restaurant orders" ON public.orders
    FOR DELETE TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

-- Assistance Requests Policies

CREATE POLICY "Customers can create assistance requests" ON public.assistance_requests
    FOR INSERT TO public
    WITH CHECK (true);

CREATE POLICY "Customers can view own assistance requests by session token" ON public.assistance_requests
    FOR SELECT TO public
    USING (true);

CREATE POLICY "Staff can view restaurant assistance requests" ON public.assistance_requests
    FOR SELECT TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

CREATE POLICY "Staff can update restaurant assistance requests" ON public.assistance_requests
    FOR UPDATE TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

CREATE POLICY "Staff can delete restaurant assistance requests" ON public.assistance_requests
    FOR DELETE TO authenticated
    USING (restaurant_id = get_user_restaurant_id());

-- SEED DATA SCRIPT --

-- Insert Dummy Restaurant
INSERT INTO public.restaurants (id, name) VALUES 
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'TableNet Demo Restaurant')
ON CONFLICT DO NOTHING;

-- Insert 15 Static Tables
INSERT INTO public.tables (restaurant_id, table_number, qr_token) VALUES
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1', 'tbl_abc001'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '2', 'tbl_abc002'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '3', 'tbl_abc003'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '4', 'tbl_abc004'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '5', 'tbl_abc005'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '6', 'tbl_abc006'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '7', 'tbl_abc007'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '8', 'tbl_abc008'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '9', 'tbl_abc009'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '10', 'tbl_abc010'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '11', 'tbl_abc011'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '12', 'tbl_abc012'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '13', 'tbl_abc013'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '14', 'tbl_abc014'),
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '15', 'tbl_abc015');
